# DQN Hyperparameters
learning_rate: 0.0005
buffer_size: 50000
learning_starts: 1000
batch_size: 64
tau: 0.01 # target network update coefficient
gamma: 0.99 # discount factor
train_freq: 4
gradient_steps: 1
exploration_fraction: 0.1
exploration_initial_eps: 1.0
exploration_final_eps: 0.05
policy: "MlpPolicy"
timesteps: 5000
